MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
  ACTIVATION_FUN: silu
ANYNET:
  STEM_TYPE: simple_stem_in
  STEM_W: 48
  STEM_K: 3
  BLOCK_TYPE: mbconv
  STRIDES: [[1, 1], [2, 2], [2, 2], [2, 2], [1, 1], [2, 2], [1, 1]]
  DEPTHS: [[3, 3], [5, 5], [5, 5], [7, 7], [7, 7], [9, 9], [3, 3]]
  WIDTHS: [[24, 24], [40, 40], [64, 64], [128, 128], [176, 176], [304, 304], [512, 512]]
  BOT_MULS: [1, 6, 6, 6, 6, 6, 6]
  KERNELS: [3, 3, 5, 3, 5, 5, 3]
  HEAD_W: 2048
  DEVICES: ["cpu", "gpu"]
  HEAD_DEVICE: "cpu"
  STEM_DEVICE: "cpu"
  MERGE_DEVICE: "cpu"
  ORIGINAL_WIDTHS: [48, 80, 128, 256, 352, 608, 1024]
  SE_ON: True
TRAIN:
  DATASET: imagenet
  IM_SIZE: 456
  BATCH_SIZE: 64
