MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
  ACTIVATION_FUN: silu
ANYNET:
  STEM_TYPE: simple_stem_in
  STEM_W: 48
  STEM_K: 3
  BLOCK_TYPE: mbconv
  STRIDES: [[1], [2], [2], [2], [1], [2], [1]]
  DEPTHS: [[2], [4], [4], [6], [6], [8], [2]]
  WIDTHS: [[24], [32], [56], [112], [160], [272], [448]]
  BOT_MULS: [1, 6, 6, 6, 6, 6, 6]
  KERNELS: [3, 3, 5, 3, 5, 5, 3]
  HEAD_W: 1792
  DEVICES: ["cpu"]
  HEAD_DEVICE: "cpu"
  STEM_DEVICE: "cpu"
  MERGE_DEVICE: "cpu"
  ORIGINAL_WIDTHS: [24, 32, 56, 112, 160, 272, 448]
  SE_ON: True
TRAIN:
  DATASET: imagenet
  IM_SIZE: 380
  BATCH_SIZE: 64
