MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STEM_K: 3
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [[2], [2], [2], [2]]
  DEPTHS: [[2], [5], [14], [2]]
  WIDTHS: [[80], [240], [560], [1360]]
  BOT_MULS: [1, 1, 1, 1]
  GROUP_WS: [[40], [40], [40], [40]]
  DEVICES: ["cpu"]
  HEAD_DEVICE: 0
  STEM_DEVICE: 0
  MERGE_DEVICE: 0
  ORIGINAL_WIDTHS: [80, 240, 560, 1360]
