MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STEM_K: 3
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [[2], [2], [2], [2]]
  DEPTHS: [[1], [3], [7], [5]]
  WIDTHS: [[64], [128], [288], [672]]
  BOT_MULS: [1, 1, 1, 1]
  GROUP_WS: [[16], [16], [16], [16]]
  DEVICES: ["cpu"]
  HEAD_DEVICE: 0
  STEM_DEVICE: 0
  MERGE_DEVICE: 0
  ORIGINAL_WIDTHS: [64, 128, 288, 672]
