MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: simple_stem_in
  STEM_W: 32
  STEM_K: 3
  BLOCK_TYPE: res_bottleneck_block
  STRIDES: [[2, 2], [2, 2], [2, 2], [2, 2]]
  DEPTHS: [[2, 2], [4, 5], [8, 14], [2, 2]]
  WIDTHS: [[40, 40], [160, 160], [480, 280], [960, 720]]
  BOT_MULS: [1, 1, 1, 1]
  GROUP_WS: [[40, 40], [40, 40], [40, 40], [40, 40]]
  DEVICES: ["cpu", "dsp"]
  HEAD_DEVICE: 0
  STEM_DEVICE: 0
  MERGE_DEVICE: 0
  ORIGINAL_WIDTHS: [80, 320, 760, 1680]
