MODEL:
  TYPE: mbanynet
  NUM_CLASSES: 1000
ANYNET:
  STEM_TYPE: res_stem_in
  STEM_W: 24
  STEM_K: 3
  HEAD_W: 1024
  BLOCK_TYPE: inverted_residual
  STRIDES: [[2, 2], [2, 2], [2, 2]]
  DEPTHS: [[4, 4], [8, 8], [4, 4]]
  WIDTHS: [[116, 116], [232, 232], [464, 464]]
  BOT_MULS: [1, 1, 1]
  GROUP_WS: [[1, 1], [1, 1], [1, 1]]
  DEVICES: ["gpu", "cpu"]
  ORIGINAL_WIDTHS: [116, 232, 464]
OPTIM:
  LR_POLICY: cos
  BASE_LR: 0.2
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 5e-5
TRAIN:
  DATASET: imagenet
  IM_SIZE: 224
  BATCH_SIZE: 256
TEST:
  DATASET: imagenet
  IM_SIZE: 256
  BATCH_SIZE: 200
NUM_GPUS: 8
OUT_DIR: .
